title: Saad Hassan
url: "https://maliksh7.github.io"
baseurl: ""
repository: maliksh7/maliksh7.github.io
markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Blog"
   link: "https://saadmalik7.wordpress.com"
 - name: "Gallery"
   link: "photos"
 - name: "Resume"
   link: "Muhammad's Resume.pdf"
 - name: "Contact"
   link: "contact"
